name: tradelog
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  intl: ^0.18.0
  provider: ^6.0.4
  responsive:
    git:
      url: https://www.github.com/berkobob/responsive
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
